import type { Destination } from "@/types";

export const DESTINATIONS: Destination[] = [
  {
    id: "rio",
    city: "Rio de Janeiro",
    country: "Brasil",
    categories: ["praia", "natureza", "familia"],
    image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800&q=80",
    climate: "Tropical, 24°C-32°C",
    avgCostPerDay: 350,
    currency: "BRL",
    language: "Português",
    funFact: "O Cristo Redentor é uma das 7 Maravilhas do Mundo Moderno.",
    rating: 4.7,
    trending: true,
  },
  {
    id: "paris",
    city: "Paris",
    country: "França",
    categories: ["europa", "romantico", "luxo"],
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80",
    climate: "Temperado, 5°C-25°C",
    avgCostPerDay: 900,
    currency: "EUR",
    language: "Francês",
    funFact: "A Torre Eiffel muda de tamanho conforme a temperatura, cerca de 15cm.",
    rating: 4.8,
    promo: { label: "Baixa temporada", discountPct: 18 },
  },
  {
    id: "tokyo",
    city: "Tóquio",
    country: "Japão",
    categories: ["asia", "luxo", "aventura"],
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    climate: "Quatro estações, -2°C-30°C",
    avgCostPerDay: 750,
    currency: "JPY",
    language: "Japonês",
    funFact: "Tóquio tem mais estrelas Michelin que qualquer outra cidade do mundo.",
    rating: 4.9,
    trending: true,
  },
  {
    id: "aspen",
    city: "Aspen",
    country: "Estados Unidos",
    categories: ["neve", "luxo", "aventura"],
    image: "https://images.unsplash.com/photo-1519904981063-b0cf448d479e?w=800&q=80",
    climate: "Alpino, -10°C-20°C",
    avgCostPerDay: 1200,
    currency: "USD",
    language: "Inglês",
    funFact: "É um dos destinos de esqui mais exclusivos do mundo.",
    rating: 4.6,
  },
  {
    id: "bali",
    city: "Bali",
    country: "Indonésia",
    categories: ["praia", "natureza", "aventura"],
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    climate: "Tropical, 26°C-33°C",
    avgCostPerDay: 300,
    currency: "IDR",
    language: "Indonésio",
    funFact: "Bali tem mais de 20.000 templos hindus espalhados pela ilha.",
    rating: 4.7,
    promo: { label: "Semana do viajante", discountPct: 22 },
  },
  {
    id: "santorini",
    city: "Santorini",
    country: "Grécia",
    categories: ["europa", "romantico", "praia"],
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80",
    climate: "Mediterrâneo, 15°C-32°C",
    avgCostPerDay: 650,
    currency: "EUR",
    language: "Grego",
    funFact: "A ilha é o resultado de uma das maiores erupções vulcânicas da história.",
    rating: 4.9,
  },
  {
    id: "patagonia",
    city: "Bariloche",
    country: "Argentina",
    categories: ["natureza", "aventura", "neve"],
    image: "https://images.unsplash.com/photo-1531065208531-4036c0dba3ca?w=800&q=80",
    climate: "Frio temperado, -2°C-20°C",
    avgCostPerDay: 400,
    currency: "ARS",
    language: "Espanhol",
    funFact: "A região tem mais de 15 lagos de origem glacial.",
    rating: 4.6,
  },
  {
    id: "orlando",
    city: "Orlando",
    country: "Estados Unidos",
    categories: ["familia", "america", "aventura"],
    image: "https://images.unsplash.com/photo-1597466599360-3b9775841aec?w=800&q=80",
    climate: "Subtropical, 15°C-33°C",
    avgCostPerDay: 550,
    currency: "USD",
    language: "Inglês",
    funFact: "É a cidade com maior concentração de parques temáticos do planeta.",
    rating: 4.5,
    trending: true,
  },
  {
    id: "marrakech",
    city: "Marrakech",
    country: "Marrocos",
    categories: ["aventura", "luxo", "natureza"],
    image: "https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=800&q=80",
    climate: "Semiárido, 12°C-38°C",
    avgCostPerDay: 380,
    currency: "MAD",
    language: "Árabe/Francês",
    funFact: "Os souks de Marrakech existem desde o século XI.",
    rating: 4.6,
    promo: { label: "Oferta relâmpago", discountPct: 15 },
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  praia: "Praia",
  neve: "Neve",
  europa: "Europa",
  asia: "Ásia",
  america: "América",
  natureza: "Natureza",
  luxo: "Luxo",
  aventura: "Aventura",
  romantico: "Romântico",
  familia: "Família",
};
